
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jun 27 13:42:18 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 44;
  public static final int CONST = 20;
  public static final int YIELD = 18;
  public static final int CASE = 15;
  public static final int NOTEQUAL = 31;
  public static final int LPAREN = 40;
  public static final int SEMI = 37;
  public static final int GREATER = 33;
  public static final int CONTINUE = 13;
  public static final int LESS = 32;
  public static final int MINUS = 26;
  public static final int RPAREN = 41;
  public static final int AND = 28;
  public static final int OR = 29;
  public static final int COMMA = 39;
  public static final int CLASS = 16;
  public static final int INC = 21;
  public static final int DIV = 24;
  public static final int PLUS = 25;
  public static final int LESSEQ = 34;
  public static final int IF = 8;
  public static final int DOT = 46;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int RBRACKET = 45;
  public static final int EQUAL = 36;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int ISEQUAL = 30;
  public static final int MUL = 23;
  public static final int NUMBER = 49;
  public static final int MOD = 27;
  public static final int IDENT = 47;
  public static final int BREAK = 12;
  public static final int VOID = 5;
  public static final int SWITCH = 14;
  public static final int COLON = 38;
  public static final int LBRACE = 42;
  public static final int ELSE = 9;
  public static final int READ = 6;
  public static final int CHARCONST = 48;
  public static final int WHILE = 11;
  public static final int DEFAULT = 19;
  public static final int RBRACE = 43;
  public static final int BOOLCONST = 50;
  public static final int EXTENDS = 17;
  public static final int PROG = 2;
  public static final int GREATEREQ = 35;
  public static final int DEC = 22;
  public static final int PRINT = 3;
  public static final int DO = 10;
}

